"""Post Engine package exports.

The public interview surface is V4 only. Non-interview runtime contracts stay
here for callers that construct generation, segmentation, and evaluation flows.
"""
from .interview import (
    DIMENSION_CATALOG,
    AuthorialDimension,
    AuthorialSignal,
    DeepeningDecision,
    DeterministicAssessment,
    DimensionScore,
    Evidence,
    Gap,
    GatewayResult,
    InterviewController,
    InterviewState,
    LlmAssessment,
    QuestionCandidate,
    SelectedQuestion,
    ThemeContext,
    UserAnswer,
    assess_dimensions,
    build_briefing,
    build_interview_ui,
    criar_estado_inicial,
    evaluate_gateway,
)
from .schemas import (
    AgentResult,
    AvaliacaoSlideMark,
    FERRAMENTAS_VALIDAS,
    GenerationPromptInput,
    INTERVIEW_SCHEMA_VERSION,
    SANDBOXES_VALIDOS,
    SESSION_SCHEMA_VERSION,
    ScoreDoPost,
    SegmentoPost,
    SlideContent,
    SugestaoImagem,
    TIPOS_DE_POST_VALIDOS,
    TrechoFraco,
    TuiSessionState,
    migrate_tipo_de_post,
)

__all__ = [
    "AgentResult",
    "AvaliacaoSlideMark",
    "DIMENSION_CATALOG",
    "AuthorialDimension",
    "AuthorialSignal",
    "DeepeningDecision",
    "DeterministicAssessment",
    "DimensionScore",
    "Evidence",
    "FERRAMENTAS_VALIDAS",
    "Gap",
    "GatewayResult",
    "GenerationPromptInput",
    "INTERVIEW_SCHEMA_VERSION",
    "InterviewController",
    "InterviewState",
    "LlmAssessment",
    "QuestionCandidate",
    "SANDBOXES_VALIDOS",
    "SESSION_SCHEMA_VERSION",
    "ScoreDoPost",
    "SegmentoPost",
    "SelectedQuestion",
    "SlideContent",
    "SugestaoImagem",
    "TIPOS_DE_POST_VALIDOS",
    "ThemeContext",
    "TrechoFraco",
    "TuiSessionState",
    "UserAnswer",
    "assess_dimensions",
    "build_briefing",
    "build_interview_ui",
    "criar_estado_inicial",
    "evaluate_gateway",
    "migrate_tipo_de_post",
]
